# Jean pockets

Are women jean pockets ridiculously small? Let's look at the data!

The file `jean-pocket-measurements.csv` shows pocket measurements for 20 popular brands.
Four pairs of jeans from each brand were measured: men's and women's skinny and straight styles. All jeans were designated a 32-inch waistband. 

The following measurements are included:
- `height_front`: maximum front pocket height (cm)
- `height_back`: maximum back pocket height (cm)
- `width_front`: maximum front pocket width (cm)
- `width_back`: maximum back pocket width (cm)

In [1]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'jean-pocket-measurements.csv'.

# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd
df = pd.read_csv('jean-pocket-measurements.csv')
df.head()

,brand,style,gender,height_front,width_front,height_back,width_back
0,3fe5003e,skinny,women,14.5,16.5,15.0,13.7
1,3fe5003e,straight,women,14.5,16.0,15.5,13.0
2,790c6eab,skinny,women,13.0,14.5,15.5,13.5
3,790c6eab,straight,women,13.0,14.5,14.5,13.0
4,26aaf627,skinny,women,13.0,14.0,14.0,14.2

### Project Ideas

- What is the average difference in pocket `height_front` between women's and men's jeans?

- Is there a significant difference in pocket `height_front` between skinny and straight styles within the same gender?

- How do back pocket sizes compare between women's and men's jeans?

- Measure your phone's height. What percentage of women's and men's jeans can comfortably fit your phone in the pockets?

Question 1: What is the average difference in pocket `height_front` between women's and men's jeans?

In [3]:
average = df.groupby('gender')['height_front'].mean()
ave_diff = abs(average['men']-average['women'])
ave_diff

np.float64(8.802500000000002)

Question 2: Is there a significant difference in pocket `height_front` between skinny and straight styles within the same gender?

In [4]:
from scipy.stats import ttest_ind

In [11]:
#for women
#for women
women = df.query('gender == "women"')

skinny = women.query('style == "skinny"')['height_front']
straight = women.query('style == "straight"')['height_front']

t_stat, p_value = ttest_ind(skinny, straight)
print('t_stat =', t_stat,', p_value =', p_value)

t_stat = -0.17115809415789315 , p_value = 0.8650076245237605

p-value is greater than 0.05, we fail to reject the null hypothesis. This means that there is no significant difference in the front pocket height between skinny and straight jeans for women.

In [13]:
#for men
men = df.query('gender == "men"')

skinny1 = men.query('style == "skinny"')['height_front']
straight1 = men.query('style == "straight"')['height_front']

t_stat, p_value = ttest_ind(skinny1, straight1)
print('t_stat =', t_stat,', p_value =', p_value)

t_stat = 0.1667094755117798 , p_value = 0.8684825879248874

p-value is greater than 0.05, we fail to reject the null hypothesis. This means that there is no significant difference in the front pocket height between skinny and straight jeans for men.

Question 3: How do back pocket sizes compare between women's and men's jeans?

In [8]:
df.groupby('gender')[['height_back','height_front']].mean()

        height_back  height_front
gender
men         16.0075       23.1300
women       15.1225       14.3275

In average, men's jeans have back pockets that are approximately 1 cm longer than those of women's jeans. Similarly, their front pockets are about 9 cm longer.

Question 4: Measure your phone's height. What percentage of women's and men's jeans can comfortably fit your phone in the pockets?

In [9]:
phone_height = 15 #15cm height of a phone

df['phone_fit'] = df['height_front'] >= phone_height #True = 1, False = 0.

df.groupby('gender')['phone_fit'].mean() * 100

gender
men      100.0
women     30.0
Name: phone_fit, dtype: float64

All of the men's jeans (100%) can fit a 15 cm phone in their front pockets, whereas only 30% of the women's jeans can.